### PR TITLE
Milestone 4: The Clone of the Apple Page

### PR DESCRIPTION
**Pull request by OdongAlican**
### Technologies used
This project is developed in the following technologies
- HTML5 and CSS3
- Stylelint and W3C Markup Validator

### CODE REVIEW

**Comment by OdongAlican** [comment]
Hi @rOluochKe. Thanks a lot for the response. I have made the changes for the nested section tags and replaced them with div tags

**Comment by thsvr** [comment]
Project under review by Thaís Vieira (TSE)

**Comment by thsvr** [comment]
### **Status: PROJECT APPROVED** :1st_place_medal: :1st_place_medal: :1st_place_medal: 

Hi @OdongAlican ! Your jobs looks amazing and it is approved, congratulations :smiley: :smiley: :smiley: 

Before merge it to master and submit it, can you please fix a small thing?

:v:  As Raymond told you above, it is better if you not nest `<section> `tag into `<section>` tag. On the line 14 (HTML) you have a tag `<section class="container">` with a child `<section class="background">` .
If you replace the`<section class="background">` with `<article> `tag it will be more appropriate. 

**So, I trust you will do this change before submit, so no need to send the code for review again, your project is approved!**

### **Keep doing an amazing job** :100: and ** good luck on the next project** :fireworks: :fireworks: 

###  **Happy coding** :computer: 

If you have any questions, don't hesitate to contact me through slack [@Thaís Vieira Azevedo ](url)

Thaís Vieira (TSE)

**Comment by OdongAlican** [comment]
Hi @thsvr. Thanks a lot for the review. Sorry, I had skipped that. I have fixed the recommended changes.

**Pull request merged**
